name: "Github Release"
on:
  push:
    branches:
      - "2.0"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run zip --if-present

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            quick-javascript-switcher.zip


# - name: Chrome Extension upload & publish
#   uses: Passiverecords/chrome-extension-upload-action@1.4.1
#   with:
#     refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
#     client-id: 'xxxxxxxxxxxxx'
#     client-secret: 'xxxxxxxxxxxx'
#     file-name: './extension.zip'
#     app-id: 'geddoclleiomckbhadiaipdggiiccfje'
#     publish: false